### ISSUE TITLE
question about kitti

### ISSUE THREAD

**Issue by BigTeacher-777** [tianweiy/MVP#1]
could you release the kitti code？

**Comment by tianweiy** [comment]
I can, but as it uses another codebase, I will need a few weeks to clean up and release the code

**Comment by suyeH** [comment]
> Still busy with some school interviews, I will clean up and release once I finish them

Hi, thanks for your work, is there any progress on the kitti code?

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/MVP/issues/20
