### ISSUE TITLE
Rotation TTA

### ISSUE THREAD

**Issue by PLester** [tianweiy/MVP#10]
Could you please share how to do Rotation TTA , eg. [+-6.25°, +-12.5°]
I cannot get the correct results for many many tests.

**Comment by tianweiy** [comment]
https://github.com/tianweiy/CenterPoint/issues/140#issuecomment-834394326

**Comment by PLester** [comment]
SUPER useful, thanks!

**Comment by tianweiy** [comment]
sure, congratulations for the good results on the leaderboard

**Comment by PLester** [comment]
Thanks! Standing on the shoulders of giants.
