### ISSUE TITLE
No module named 'CenterNet2'

### ISSUE THREAD

**Issue by kdibra7** [tianweiy/MVP#11]
I have installed Detectron2 , CenterPoint and CenterNet2, But while running virtual_gen.py in the mvs root folder I get this error "No module named 'CenterNet2'.

I have already added the paths of CenterPoint and CenterNet2.

**Comment by tianweiy** [comment]
> I have already added the paths of CenterPoint and CenterNet2

How do you do this step? Pretty sure the problem is with the path

**Comment by kdibra7** [comment]
I have added the path of CenterPoint in my .bashrc file.

**Comment by tianweiy** [comment]
The problem is with centernet2. Please paste your exact comment

**Comment by tianweiy** [comment]
you need a export pythonpath to this specific folder https://github.com/xingyizhou/CenterNet2/tree/master/projects/CenterNet2

**Comment by kdibra7** [comment]
> > I have already added the paths of CenterPoint and CenterNet2
> 
> How do you do this step? Pretty sure the problem is with the path

Thank you for your quick responses.  I have set the PYTHONPATH as follows
export PYTHONPATH="/path/to/centernet2"

**Comment by tianweiy** [comment]
yeah, make sure it is to the specific folder. (instead of just the root directory of centernet2)

**Comment by qnH6** [comment]
> you need a export pythonpath to this specific folder https://github.com/xingyizhou/CenterNet2/tree/master/projects/CenterNet2

Trying to do this, but got 404 Error. 
The 'xingyizhou/CenterNet2' repository doesn't contain the 'projects/CenterNet2' path in 'master'.
