### ISSUE TITLE
question about centernet2

### ISSUE THREAD

**Issue by Liaoqing-up** [tianweiy/MVP#12]
hello, tianweiy! Can you share how you train the model **Centernet2**, and how about the performance, like miou ....Thankyou!

**Comment by tianweiy** [comment]
sorry I missed this issue. 

You can use this config for training centernet2 https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/configs/nuImages_CenterNet2_DLA_640_8x.yaml 

you will need to first convert nuimage to coco format following https://github.com/open-mmlab/mmdetection3d/tree/master/configs/nuimages

The model gets 43.3 map on nuimage val set

**Comment by Liaoqing-up** [comment]
ok, i see. Thankyou, tianweiy always respond ~

**Comment by Adam1904** [comment]
Hello,
How about NuScenes, can you share how to convert NuScenes to coco format?
