### ISSUE TITLE
How is the FPS of MVP?

### ISSUE THREAD

**Issue by buaacyw** [tianweiy/MVP#13]
I'm curious about the FPS of MVP. Is it much slower than pure centerpoint?

**Comment by tianweiy** [comment]
I don't have exact number but it is slower as we need to run a 2d model on top of 6 camera images. So the runtime is like 6 * CenterNet + 1 * CenterPoint + 5~10ms for virtual point generation.

**Comment by buaacyw** [comment]
Thanks！

**Comment by zyl1336110861** [comment]
@tianweiy The CenterNet is very slow.

**Comment by tianweiy** [comment]
Well, it depends(on your definition of slow). It is 40fps(for one image) in our setup and different image could be pipelined in real deployment.

**Comment by zyl1336110861** [comment]
How can you achieve 40fps??? So amazing.

**Comment by zyl1336110861** [comment]
OK! Thank you, I will have a try. Making the total model real-time is so hard.

**Comment by zyl1336110861** [comment]
OK! Thank you, I will have a try. Making the total model real-time is so hard especially on Xavier.

**Comment by tianweiy** [comment]
Well, I suggest using lidar only model on Xavier then. Any camera will be too slow..

**Comment by zyl1336110861** [comment]
OK!
