### ISSUE TITLE
nuImages 2D annotation aligned with nuScenes camera data

### ISSUE THREAD

**Issue by SxJyJay** [tianweiy/MVP#14]
Thanks for your great work and released code!
I am wondering if there are any methods to align the camera images in nuScences with those in nuImages. Since I observed that roughly 76% virtual points, selected according to CenterNet2's instance segmentation masks, are discarded because that they don't correspond to any instances annotated in the nuScenes. Hence, I am wondering the influence of the discrepancy between the instances detected by CenterNet2 and those annotated in the nuScenes, and would like to know if there are any possible ways to directly obtain the 2D annotations of camera images within the nuScenes?

**Comment by tianweiy** [comment]
> I am wondering if there are any methods to align the camera images in nuScences with those in nuImages.

I think most data only appears in one of nuscenes and nuimage so there is no way to align them.

> Since I observed that roughly 76% virtual points, selected according to CenterNet2's instance segmentation masks, are discarded because that they don't correspond to any instances annotated in the nuScenes

I didn't get this. Where are they discarded? 

> Hence, I am wondering the influence of the discrepancy between the instances detected by CenterNet2 and those annotated in the nuScenes, and

It is possible that virtual points are not inside any 3d objects due to the depth error. I don't know if there are inherent difference for annotation though

> and would like to know if there are any possible ways to directly obtain the 2D annotations of camera images within the nuScenes?

Not in my mind. If the point cloud is denser, we can probably do back projection to get instance mask. However, they are too sparse now

**Comment by SxJyJay** [comment]
Thanks for your reply.

>  I didn't get this. Where are they discarded?

The raw virtual points are selected from 2D instance segmentation mask. And these segmented instances are not strictly consistent with the annotations in nuScenes. Thus, virtual points within the instance which don't exist in nuScenes' annotation are discarded.

The specific code of this part are line 119-121 in virtual_gen.py, where the 'dist_thresh' filters the virtual points I referred above.
https://github.com/tianweiy/MVP/blob/f90fcb8e94cc67ebb368902f7d51cea99c2a2436/virtual_gen.py#L119

As for the 2D annotations in the nuScenes, I just want to double check whether I miss relevant details in this dataset as I don't find them.

I am clear with the question
