### ISSUE TITLE
How did you visualize the pcd.bin.pkl.npy files of virtual points?

### ISSUE THREAD

**Issue by prizehun** [tianweiy/MVP#15]
Thank you for your great job.
I want to visualize them and then compare with original points.
Can i have some tips?

**Comment by tianweiy** [comment]
Just draw it with open3d https://github.com/tianweiy/CenterPoint/blob/d1e1bd5b08b2b9816ee38bbe2d036db1e5df340a/tools/visual.py#L64

**Comment by prizehun** [comment]
And i have idea to draw pcd or bin files using open3d but i don't know how to draw with pcd.bin or pcd.bin.pkl.npy files like this.

**Comment by tianweiy** [comment]
You first load them using np.load. it is a dict.

**Comment by prizehun** [comment]
Thank you! I can draw points with open3d in my way using dictionary. But there is only three keys 'virtual_points', 'real_points', 'real_points_indice' and i think 'detections', 'scores' keys is only in your visual.py codes. How can i use detections and scores to plot boxes??
Thank you for your help :)

**Comment by lilyuehao** [comment]
> Thank you! I can draw points with open3d in my way using dictionary. But there is only three keys 'virtual_points', 'real_points', 'real_points_indice' and i think 'detections', 'scores' keys is only in your visual.py codes. How can i use detections and scores to plot boxes?? Thank you for your help :)

The output contains one-hot encoded instance segmentation results, which you can use to colorize the point cloud
