### ISSUE TITLE
CenterPoint+PointPainting on nuScenes Val dataset

### ISSUE THREAD

**Issue by buaacyw** [tianweiy/MVP#17]
Hi! Thanks for your paper MVP.
But I have a question about the result of CenterPoint+PointPainting on nuScenes Val dataset.
As you mentioned in the paper, it reaches 66.5 overall mAP. But my result is only 65.4.
I train the model by just throwing away those virtual points since you have already painted those real points on the masks.
All other configurations are the same with https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_scale_virtual.py

Could you please tell me the reason? Thanks!

**Comment by buaacyw** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0dae4fbb-ef02-419c-88a2-051ada39e914/Untitled.png)

**Comment by buaacyw** [comment]
![image](https://user-images.githubusercontent.com/52091468/163786910-953af1d1-83e6-44aa-9930-8d89d4835b1f.png)

**Comment by tianweiy** [comment]
Hi, in the table, we also do the same second stage for point painting. For single stage, your number seems right

**Comment by buaacyw** [comment]
Thanks for your quick reply!
As for the second stage, I find in https://github.com/tianweiy/CenterPoint/blob/d1e1bd5b08b2b9816ee38bbe2d036db1e5df340a/configs/mvp/nusc_two_stage_base_with_virtual.py#L278 that you have only trained 6 epochs. Does that mean you first only train one stage for 20 epochs and then resume from those parameters and train the second stage for 6 epochs?

**Comment by tianweiy** [comment]
Yes, set the weight trained using first stage at https://github.com/tianweiy/CenterPoint/blob/d1e1bd5b08b2b9816ee38bbe2d036db1e5df340a/configs/mvp/nusc_two_stage_base_with_virtual.py#L27

**Comment by buaacyw** [comment]
Thanks!
And I found that you haven't removed those raw points which are within those masks and are painted. For MVP, I think you keep those raw points for split voxelization. But just for CenterPoint+PointPainting, why not remove those raw points away?

**Comment by tianweiy** [comment]
This also works. I just keep the comparison the same as our approach in table 4.

**Comment by buaacyw** [comment]
Thanks!
