### ISSUE TITLE
question about MaskFormer pretrained model.

### ISSUE THREAD

**Issue by jqfromsjtu** [tianweiy/MVP#20]
Hi! Thank you for your work!
1.  I'm trying to reproduce the results of MVP-KITTI in your paper, could you provide more information about the pretrained MaskFormer model? Which one should I choose to get the same result as you did. 
2. Also, there are some slight differences in results trained with PointPillars and KITTI. I used PointPillars in CenterPoint-KITTI which has the same config file as the one in your OpenPCdet. All settings are default. Also I download the pretrained model in https://github.com/tianweiy/OpenPCDet (model-18M) and get the results as below. The download model gets the same results as documented in your web but I record the Car_R40_moderate_0.7 instead of Car_moderate_0.7 so I can compare it with my result.

Method | Car@R40_moderate | Cyclist@R40_moderate | Pedestrian@R40_moderate
PointPillars(my training) | 77.4143 | 64.2696 | 50.4214
PointPillars(download) | 78.3964 | 62.8074 | 51.4145
PointPillars(in paper) | 77.3 | 62.7 | 52.3

How can I get the results in your paper? Are there any changes I need to make?

**Comment by tianweiy** [comment]
1. i use one of the coco model with swin (either B or L, I don't remember exactly).
![image](https://user-images.githubusercontent.com/38497390/167331795-c694a148-6176-4607-9ec5-677f6c02b29b.png)

2. I simply took the baseline number from openpcdet. 
![image](https://user-images.githubusercontent.com/38497390/167331975-9ffc8d9f-a589-4ace-9785-bea86b39ebb1.png)
I noticed there are up to 1 point variations so it is also possible that a new iteration of training differs from download/paper results. Additionally, it seems that results with Car / Cyclists training are more stable than the training with all three classes. 

I will push the code soon (probably after neurips deadline). Most things are ready but I still need to test them a bit.

**Comment by vehxianfish** [comment]
@tianweiy  Thanks for your wonderful work and patient explanation. Are the docs released later?  Thanks, again.

**Comment by tianweiy** [comment]
I will add some tonight. Thanks for the interest!

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/OpenPCDet/blob/master/VIRTUAL_KITTI.md

**Comment by mytk2012** [comment]
你好，我复现VIRTUAL_KITTI.md里的代码，但是发现python demo/demo.py   --input ../data/kitti/training/image_2  --output ../data/kitti/training/seg_2/   MODEL.WEIGHTS model_final_7505c4.pkl，这里demo.py设置的config文件并没有，detectron2里也没相关文件代码，包括参数MODEL.WEIGHTS model_final_7505c4.pkl也是，请问这是完整的md吗？

**Comment by tianweiy** [comment]
应该是这个folder https://github.com/facebookresearch/MaskFormer/tree/main/configs 

然后模型应该是这个里面的link 下载的 https://github.com/tianweiy/OpenPCDet/blob/master/VIRTUAL_KITTI.md

PS：MVP这个repo 已经很老很老了，你可能可以看看一些最新的follow up 方法 e.g. https://arxiv.org/pdf/2303.02314.pdf 效果应该是好不少的
