### ISSUE TITLE
virtual points and points features alignment

### ISSUE THREAD

**Issue by jqfromsjtu** [tianweiy/MVP#21]
Hi! Thank you for your work. I'm looking at the code and find that lidar points' features are not exactly aligned: 
virtual_points1 = data_dict['real_points'][:, [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]] 
virtual_points2 = data_dict['virtual_points']
points = np.concatenate([points, np.ones([points.shape[0], 15-num_point_feature])], axis=1)
virtual_points1 = np.concatenate([virtual_points1, np.zeros([virtual_points1.shape[0], 1])], axis=1)
virtual_points2 = np.concatenate([virtual_points2, -1 * np.ones([virtual_points2.shape[0], 1])], axis=1)
points = np.concatenate([points, virtual_points1, virtual_points2], axis=0).astype(np.float32)

So I wondered why not using orders like below (x, y, z, intensity(-1 for virtual points2), classification*10, score):
virtual_points1 = data_dict['real_points'][:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]
virtual_points2 = data_dict['virtual_points']
virtual_points2 = np.concatenate([virtual_points2[:, [0, 1, 2]] , -1 * np.ones([virtual_points2.shape[0], 1]), virtual_points2[:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]], axis=1)

**Comment by tianweiy** [comment]
yeah, it seems a bit ugly. But I think we have some postprocessing later to make them aligned. Maybe you can first check https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/models/readers/dynamic_voxel_encoder.py#L22 

let me know if it still seems not aligned after that

**Comment by jqfromsjtu** [comment]
I see it expanded points' features from 4/14/15 into 22 so different features could be aligned, but I couldn't find a similar operation in pillar_encoder.py:
https://github.com/tianweiy/CenterPoint/blob/8fcdc944bbb455bd25943b331aaf961aa0ab32cd/det3d/models/readers/pillar_encoder.py#L119
It only changed the last feature of virtual points, but the other features were still misaligned, I assume.

**Comment by tianweiy** [comment]
you are right. I guess for pointpillar as it gets a linear layer to aggregate feature so it is probably fine with this small misalignment

**Comment by jqfromsjtu** [comment]
Hi! I'm still working on PointPillars+MVP with KITTI and can't get results as expected. Here are my steps and I hope you can give me some advice, plzzzzz.
The pipeline of PointPillars+MVP+KITTI:
1. 2D segmentation: 
	CenterNet2 model provided by the author, no visible drawbacks of instances with KITTI, currently using this model for experiments
	Mask2Former model download from the model zoo, no visible drawbacks of instances with KITTI
2. Virtual points generation: 
	Revised on virtual_gen.py, same with Nuscenes' virtual points generation. I visualized painted points and virtual points with BEV and projection on image and nothing was wrong.
3. Data preparation
	Points feature alignment. I merged points procession in read_file and post-processing of lidar points in VFE into get_lidar, and they were like:
Lidar points	x	y	z	i	1	1	1	1	1	1	1	1	1	1	0
Real points	x	y	z	c	c	c	c	c	c	c	c	c	c	s	0
Virtual points	x	y	z	c	c	c	c	c	c	c	c	c	c	s	1
they were the same as post-processed points in voxels.
4. Data augmentation
	I used Lidar + Real + Virtual points to generate gt_database for later data augmentation, so I changed NUM_POINT_FEATURES in pointpillar.yaml from 4 to 15
5. Model:
	I revised VFE input/output dimensions by changing used_feature_list and src_feature_list in kitti_dataset.yaml into:
    used_feature_list: ['x', 'y', 'z', 'intensity', 
                        'class_car', 'class_truck', 'class_trailer',
                        'class_bus', 'class_vehicle', 'class_bicycle',
                        'class_motor', 'class_pedestrian', 'class_cone',
                        'class_barrier', 'score'],
    src_feature_list: ['x', 'y', 'z', 'intensity', 
                        'class_car', 'class_truck', 'class_trailer',
                        'class_bus', 'class_vehicle', 'class_bicycle',
                        'class_motor', 'class_pedestrian', 'class_cone',
                        'class_barrier', 'score'],
Am I missing something here? Also, is it possible for you to share the kitti_dataset.py, kitti_datase.yaml, pointpillar.yaml and LIDAR_POINTS_VIRTUAL of KITTI so I can better reproduce KITTI's result? Thank you very much!!!

**Comment by jqfromsjtu** [comment]
Here are my result:
KITTI metrics: 3d_R40_moderate(Car@0.7, Pedestrian@0.5, Cyclist@0.5)
PointPillars baseline 	77.9101	49.3524	63.3075
Pointpillars+CenterNet2	76.9575	35.6764	49.2403
					-0.9526	-13.676	-14.0672

**Comment by tianweiy** [comment]
Hi, most of my code for KITTI is already updated at https://github.com/tianweiy/OpenPCDet I will finish it tomorrow. 

I can get to the following stats 

![image](https://user-images.githubusercontent.com/38497390/170803877-5b919f8b-34ac-49db-b96f-156c2641ff9a.png)

**Comment by jqfromsjtu** [comment]
Oh I see these config files, thank you so much!!!!

**Comment by tianweiy** [comment]
Yeah, you still need to generate virtual point t/ gt database. I will write the full instructions for this tonight

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/MVP/issues/20
