### ISSUE TITLE
Generating results on nuscenes test set

### ISSUE THREAD

**Issue by SxJyJay** [tianweiy/MVP#22]
Hi,
   I am wondering how can I generate virtual points for nuscenes test set. Since I don't find a .pkl file like "infos_train_10sweeps_withvelo_filter_True.pkl", which seems to be required for generating virtual points with command 
```
python virtual_gen.py --info_path data/nuScenes/infos_train_10sweeps_withvelo_filter_True.pkl  MODEL.WEIGHTS centernet2_checkpoint.pth 
```

**Comment by tianweiy** [comment]
you will need to generate one following https://github.com/tianweiy/CenterPoint/blob/master/docs/NUSC.md#create-data

change the root to the test folder and change the version to 'v1.0-test'

**Comment by SxJyJay** [comment]
Thanks for your reply!
