### ISSUE TITLE
semantic information different between PointPainting and MVP

### ISSUE THREAD

**Issue by yangyt37** [tianweiy/MVP#28]
I read the code of pointpainting which is based openpcdet.It use segmentation score which is added to one to be paint point semantic information. But virtual_gen.py use one-hot encoded and classification confidence as semantic information.Is my understanding of  the code right? Which is better and why?

**Comment by yangyt37** [comment]
I use mvp to be my undergraduate graduation project baseline, however, I don't have enough computing resource, so I have to use mvp in only 1/10 nuscenes, the result is amazing! The centerpoint is  only 30 map train by 1/10 nuscenes data, but mvp can get the mvp of 52. And I find if only concat virtualpoint2 can get the map of 55, and if change the max number points of a pillar can get the map of nearly 57.

**Comment by tianweiy** [comment]
Which is better and why?

I don't know which is better. The reason I use instance segmentation (one-hot encode + confidence) is because there are only instance segmentation pretrained models on nuScenes back then.

**Comment by yangyt37** [comment]
Thank you very much!
