### ISSUE TITLE
How to implement CenterPoint + Ours(w/o virtual)

### ISSUE THREAD

**Issue by yangyt37** [tianweiy/MVP#31]
May I ask how to implement CenterPoint + Ours(w/o virtual)? Is it just to delete virtual_points2 in points = np.concatenate([points, virtual_points1, virtual_points2], axis=0).astype(np.float32) in MVP-main/CenterPoint-vir/det3d/datasets/pipelines/loading.py read_file function?

**Comment by yangyt37** [comment]
I have done the following two experiments: one is to delete semantic information (reduce the dimension to five dimensions) and preserve virtual point coordinates (preserve virt_point2); Another method is to preserve semantic information (preserve virt_points1) and delete virtual points (delete virt_point2). The result of the second method is much better than that of the first method. It seems that semantic information can improve the performance of the CenterPoint more than more virtual point.

**Comment by tianweiy** [comment]
1. yes 

2. I think the first approach won't work (and will degrade the performance). Basically, we can't just remove the semantic information as the model won't be able to distinguish virtual and real points in that stage, which hurts the localization accuracy.

It's true that semantic information improves the detection the most, but our focus here is that adding virtual points (as well as their semantic information and confidence score) can help more with the localization at long range (table 4)

**Comment by yangyt37** [comment]
Thank you very much!
