### ISSUE TITLE
Generage `data/nuScenes/infos_train_10sweeps_withvelo_filter_painted_True.pkl` file

### ISSUE THREAD

**Issue by vehxianfish** [tianweiy/MVP#32]
Hi, thanks for your excellent work.
I have trained one-stage model `nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_scale_virtual.py`. But after running `python -m torch. distributed. launch --nproc_per_node=3 ./tools/train. py configs/mvp/nusc_two_stage_base_with_virtual. py`, the error occurs"
```bash
 FileNotFoundError: [ Errno 2] No such file or directory: ' data/nuScenes/infos_tra in_10sweeps_withvelo_filter_painted_True. pkl"
```
And I train step is followed by [https://github.com/tianweiy/MVP/blob/main/README.md](https://github.com/tianweiy/MVP/blob/main/README.md) one step by step.
But exactly, the file `infos_tra in_10sweeps_withvelo_filter_painted_True. pkl` is not generated.
My data folder is organized as follows：
![0f01bd760f25cdcd6908a58d27ecf18](https://user-images.githubusercontent.com/40848953/232181266-6e1b6ca9-1988-47f8-b8dd-1e8620a96943.png)
So, what step is lacking? Thank you very much.

**Comment by tianweiy** [comment]
hi, which line of code is this error ? . Could you paste the full logs? 

In the config, the infos_train file you have now should be sufficient ? as we are using it at https://github.com/tianweiy/CenterPoint/blob/d3a248fa56db2601860d576d5934d00fee9916eb/configs/mvp/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_scale_virtual.py#L160

**Comment by mpQuintana** [comment]
Hello @tianweiy, 

I have the same issue. For the one stage detector is fine but for the second stage we need the infos file requested as it is used here: https://github.com/tianweiy/CenterPoint/blob/d3a248fa56db2601860d576d5934d00fee9916eb/configs/mvp/nusc_two_stage_base_with_virtual.py#L216

Could you share the details on how to generate infos_train_10sweeps_withvelo_filter_painted_True.pkl?

Best,
Marc

**Comment by tianweiy** [comment]
You can use the same file as one stage. Change the info path name in the config to the one stage one
