### ISSUE TITLE
generate the virtual points

### ISSUE THREAD

**Issue by Adam1904** [tianweiy/MVP#37]
Hello tianweiy,
when I generate the points with gpu RTX 3090 , I get this by train set:
 100%|█████████████████████████| 271572/271572 [110:45:35,<00:00,  1.46s/it]
and this by val set:
100%|█████████████████████████| 58066/58066 [25:44:38<00:00,  1.60s/it]

1- What does these numbers 271572,58066  mean? Is it the number of segmentation masks in the images?
num of images in val set is: 16445!

2- Why does it take so long to generate virtual points? Is this logical?

**Comment by tianweiy** [comment]
1. it is the number of frames. in nuscenes, you get 1 key frame + 10 non-key frame, so it is much larger. 

2. I am not sure. you can profile the program and see which part is the most time consuming in your setup.
