### ISSUE TITLE
Some question about find the minimum distance between virtual and real points

### ISSUE THREAD

**Issue by Liaoqing-up** [tianweiy/MVP#4]
Hi, I go over your code in details recently, but in function **add_virtual_mask**, i find it compute the distance between a virtual point and all real point then select the minimum, ignore if the real point is in the same camera_id and same mask with the virtual point. I wonder that's a little unreasonable? Because it may use a real point's depth which is in other mask or even in other camera_id. Looking forward to your reply~

**Comment by Liaoqing-up** [comment]
Sorry, now i see the methods you used to avoid the above situation! You multi a large number for the mask instance!

**Comment by tianweiy** [comment]
right, the implementation is a little hacky to avoid for loop :)
