### ISSUE TITLE
PPT

### ISSUE THREAD

**Issue by guzuoxu** [tianweiy/MVP#5]
Is it convenient to disclose the PPT in the video?

**Comment by tianweiy** [comment]
the keynote is her3
keynote
[MVP NeurIPS v4.zip](https://github.com/tianweiy/MVP/files/7638507/MVP.NeurIPS.v4.zip)
ppt 
[MVP NeurIPS v4.pptx](https://github.com/tianweiy/MVP/files/7638521/MVP.NeurIPS.v4.pptx)

**Comment by guzuoxu** [comment]
> the keynote is here keynote [MVP NeurIPS v4.zip](https://github.com/tianweiy/MVP/files/7638507/MVP.NeurIPS.v4.zip) ppt [MVP NeurIPS v4.pptx](https://github.com/tianweiy/MVP/files/7638521/MVP.NeurIPS.v4.pptx)

Thank you very much！！
