### ISSUE TITLE
Split Voxelization? Two-stage?

### ISSUE THREAD

**Issue by zwqnju** [tianweiy/MVP#6]
I have two questions about the abation study in your paper:

1) What is split voxelization?

2) Does your repo contain the code about split voxelization or two-stage method?

**Comment by tianweiy** [comment]
1. See paper for details.

2. It gets split voxelization. I will push two stage code / model at the middle of December

**Comment by tianweiy** [comment]
two stage is up here https://github.com/tianweiy/CenterPoint/blob/master/configs/mvp/nusc_two_stage_base_with_virtual.py

model is updated in the README
