### ISSUE TITLE
setting of "num_virtual"

### ISSUE THREAD

**Issue by PLester** [tianweiy/MVP#8]
Did you conduct experiments for different setting of the param "num_virtual"?
Could you explain the thinking why sets 'num_virtual = 50' ? Why not larger num_virtual, eg. num_virtual = 100, 200.

Thanks!

**Comment by tianweiy** [comment]
I never ablate this. I tried 25 and 50 and the results seem close. For larger number, I feel it may introduce more FP points. I can try to get a plot once i get time
