### ISSUE TITLE
WBF

### ISSUE THREAD

**Issue by PLester** [tianweiy/MVP#9]
Could you please share your code of "weighted boxes fusion"?

**Comment by tianweiy** [comment]
I don't have an implementation for this. I never use wbf for any projects. Why do you want this ?

**Comment by PLester** [comment]
> I don't have an implementation for this. I never use wbf for any projects. Why do you want this ?

I saw in nuscenes leaderboad, "ensemble of five models with input grid size between (0.05m,0.05m) to (0.15m, 0.15m)". 
So I want to try the performance of ensemble of 3~5 MVP models . And the most used fusion method is WBF. 
If convinent, Please advise your fusion method, you also could gvie me an email: panglei0125@163.com.

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint/issues/125

**Comment by PLester** [comment]
thanks
